### ISSUE TITLE
don't use inline styling

### ISSUE THREAD

**Issue by rimmesbe** [graceknerd/prj-rev-bwfs-dasmoto#2]
Now that we have css in our toolbelts don't use inline styling anymore. Inline styling is very hard to overwrite and it is inefficient. You can target the h2's individually through the section ids:
#brushes h2 { }

https://github.com/graceknerd/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/index.html#L14

**Comment by graceknerd** [comment]
This one, I was really confused on. I didn't want to use the inline styling, but I thought I had to since all the banners had different background colors for H2. How would I have used #brushes in html?

**Comment by rimmesbe** [comment]
You can chain selectors together:
#brushes h2 { }
means target only the h2's that are inside the element with the brushes id.
http://adam-marsden.co.uk/css-cheat-sheet/
