### ISSUE TITLE
setting page font

### ISSUE THREAD

**Issue by rimmesbe** [graceknerd/prj-rev-bwfs-dasmoto#4]
Rather that list all the elements that need to have a specific font we can just set the default font for all elements on the page with inheritance:
html { font-family: Helvetica; }
Now all elements will default to this font, very efficient.

https://github.com/graceknerd/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/resources/style.css#L1-L3

**Comment by graceknerd** [comment]
is *{ } for global elements as well?

**Comment by rimmesbe** [comment]
The * will target all elements but I don't recommend using that often. It is slow to process and pretty powerful.
