### ISSUE TITLE
good use of class

### ISSUE THREAD

**Issue by rimmesbe** [graceknerd/prj-rev-bwfs-dasmoto#5]
This ".price" class is a good usage of class and a good class name as it describes the component being styling. One thing you could do is swap the span tags for a `<strong>` tag which defaults to bold but otherwise is the same as the span.

https://github.com/graceknerd/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/resources/style.css#L20-L23

**Comment by graceknerd** [comment]
I'm going to try <strong> again next time. I originally tried it and it didn't work, so I used span, but maybe I did something wrong in the first try.
